apiVersion: v1
kind: Pod
metadata:
  name: ansible
spec:
  containers:
    - name: ansible
      image: "image-registry.openshift-image-registry.svc:5000/\
              cit-hiperautomacao/ansible:v0.8cit"
      imagePullPolicy: Always
      command:
        - tail
        - -f
        - /dev/null
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 2Gi
    - name: jnlp
      image: "image-registry.openshift-image-registry.svc:5000/\
              cit-hiperautomacao/jenkins-agent:jdk11-v0.4cit"
  nodeSelector:
    env: prd
imagePullSecrets: